### ISSUE TITLE
bug(facet-core): camino impls ownership

### ISSUE THREAD

**Issue by lmmx** [facet-rs/facet#320]
After merging commit a969a0f, the CI build for facet-core fails with:

```
error[E0599]: no method named `to_owned` found for reference `&Utf8Path` in the current scope
  --> facet-core/src/impls_camino.rs:23:82
   |
23 | Some(|s, target| Ok(unsafe { target.put(Utf8Path::new(s).to_owned()) }));
   |                                                                                  ^^^^^^^^ method not found in `&Utf8Path`
```

This says that the `ToOwned` trait (which provides `to_owned`) isn’t in scope for `&Utf8Path`. CI runs both with and without the alloc feature and fails identically.

Repros by checking out `main` branch and running

```bash
cargo check --all-targets --target-dir target/msrv --locked \
  --manifest-path facet-core/Cargo.toml --no-default-features --features camino
```
